CREATE TABLE IF NOT EXISTS users(
    id SERIAL PRIMARY KEY,
    email VARCHAR(256) NOT NULL UNIQUE,
    pass_hash VARCHAR(256) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users(email);

CREATE TABLE IF NOT EXISTS apps(
    id SERIAL PRIMARY KEY,
    name VARCHAR(256) NOT NULL,
    secret VARCHAR(256) NOT NULL
);